## NUMPY
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Using NumPy, we can perform the following operations −
    * Mathematical and logical operations on arrays.
    * Fourier transforms and routines for shape manipulation.
    * Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

Numpy provides:
    * extension package to python for multi-dimensional arrays
    * closer to hardware (efficiency)
    * designed for scientific computation (convenience)
    * also known as array oriented computing

In [1]:
import numpy as np

a1 = np.array([1, 2, 3, 4])
a2 = np.arange(10)

print(a1)
print(a2)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
# advantage of numpy array over lists
L = range(1000)
%timeit [i**2 for i in L]

A = np.arange(1000)
%timeit A**2

634 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.31 µs ± 73.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
a1 = np.array([1, 2, 3])
print('a1:', a1)
print('a1 dim:', a1.ndim)
print('a1 shape:', a1.shape)
print('a1 size:', a1.size)

a2 = np.array([[1, 2, 3], [3, 4, 5]])
print('a2:', a2)
print('a2 dim:', a2.ndim)
print('a2 shape:', a2.shape)
print('a2 size:', a2.size)

a1: [1 2 3]
a1 dim: 1
a1 shape: (3,)
a1 size: 3
a2: [[1 2 3]
 [3 4 5]]
a2 dim: 2
a2 shape: (2, 3)
a2 size: 6


In [4]:
# array creation
a1 = np.array([1, 2, 3, 4])
print('a1:', a1)
a2 = np.arange(4)
print('a2:', a2)
a3 = np.arange(1, 10, 2)     # (start, end(not included), step)
print('a3:', a3)
a4 = np.linspace(0, 1, 4)    # (start, end(included), no. of values)
print('a4:', a4)

a1: [1 2 3 4]
a2: [0 1 2 3]
a3: [1 3 5 7 9]
a4: [ 0.          0.33333333  0.66666667  1.        ]


In [5]:
# special type arrays
a5 = np.ones((3,3))
print('ones:\n', a5)
a6 = np.zeros((3,3))
print('zeros:\n', a6)
a7 = np.eye(3)
print('identity:\n', a7)
a8 = np.diag([1, 2, 3, 4])
print('diagonal:\n', a8)

ones:
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
zeros:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
identity:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [6]:
# array using random()
r1 = np.random.rand(2, 3)   # uniform random number between 0 and 1
print('uniform:\n', r1)
r2 = np.random.randn(2, 3)  # standard normal variable
print('standard:\n', r2)
r3 = np.random.uniform(1, 3, size=(2, 3))   # uniform random variable (start, end, size=(...))
print('uniform (range=1 to 3):\n', r3)
r4 = np.random.randint(1, 10, size=(2, 3))   # random intergers (start, end, size(...))
print('random integers (range= 1 to 10):\n', r4)

uniform:
 [[ 0.32559421  0.41228596  0.51716788]
 [ 0.82680237  0.88719064  0.47323966]]
standard:
 [[ 0.40864786  0.06046272 -0.31854193]
 [-1.96549881 -0.64231088 -0.76737038]]
uniform (range=1 to 3):
 [[ 1.62967504  1.78877676  1.90370297]
 [ 2.86034349  1.82774475  2.1003869 ]]
random integers (range= 1 to 10):
 [[8 7 5]
 [9 2 5]]


In [7]:
# dtype (there are few more data types than specified here)
a1 = np.array([1, 2, 3, 4])
print(a1.dtype)
a1 = a1.astype('float32')
print(a1.dtype)
a2 = np.array([1, 2, 3, 4], dtype='float64')
print(a2.dtype)
a3 = np.array([1 + 2j, 3 + 4j])
print(a3.dtype)
a4 = np.array([True, False])
print(a4.dtype)
a5 = np.array(['tom', 'harry'])
print(a5.dtype)

print(np.zeros(1).dtype)
print(np.ones(1).dtype)
print(np.eye(1).dtype)

int32
float32
float64
complex128
bool
<U5
float64
float64
float64


In [8]:
# slicing
a1 = np.arange(10)
print(a1)
a2 = a1[2:-1:2]      # [start, end, step]
print(a2)
a3 = a1[::-1]
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [9]:
# copies and views
a1 = np.arange(10)
print('a1:', a1)
a2 = a1[::2]           # creates a view -> shares memory
print('a2:', a2)
a3 = a1[::2].copy()    # creates a copy -> different memory loc
print('a3:', a3)
print('a1 and a2 shares mem:', np.shares_memory(a1, a2))
print('a1 and a3 shares mem:', np.shares_memory(a1, a3))

a2[0] = 100
print('a1:', a1)
print('a2:', a2)
print('a3:', a3)
a3[0] = 123
print('a1:', a1)
print('a2:', a2)
print('a3:', a3)

a1: [0 1 2 3 4 5 6 7 8 9]
a2: [0 2 4 6 8]
a3: [0 2 4 6 8]
a1 and a2 shares mem: True
a1 and a3 shares mem: False
a1: [100   1   2   3   4   5   6   7   8   9]
a2: [100   2   4   6   8]
a3: [0 2 4 6 8]
a1: [100   1   2   3   4   5   6   7   8   9]
a2: [100   2   4   6   8]
a3: [123   2   4   6   8]


In [10]:
# boolean masking --->> creates copy instead of view
a1 = np.arange(10)
mask = (a1 % 2 == 0)
extracted = a1[mask]
print('a1:\n', a1)
print('mask:\n', mask)
print('extracted:\n', extracted)

a1[mask] = -1
print('a1:\n', a1)

a1:
 [0 1 2 3 4 5 6 7 8 9]
mask:
 [ True False  True False  True False  True False  True False]
extracted:
 [0 2 4 6 8]
a1:
 [-1  1 -1  3 -1  5 -1  7 -1  9]


In [11]:
# indexing with array
a1 = np.array([4, 2, 7, 5, 2, 4])
print('a1:\n', a1)
a2 = a1[[3, 2, 1, 0, 3, 2, 1, 0]]
print('a2:\n', a2)
a1[[0,1]] = 100
print('a1:\n', a1)

a1:
 [4 2 7 5 2 4]
a2:
 [5 7 2 4 5 7 2 4]
a1:
 [100 100   7   5   2   4]


In [12]:
# matrix multiplication
np.random.seed(3)
a1 = np.random.randint(1, 10, (3, 3))
a2 = np.random.randint(1, 10, (3, 3))
print('a1:\n', a1)
print('a2:\n', a2)

print('a1*a2:\n', a1 * a2)     # element-wise multiplication - works only for same shaped matrix
print('a1.dot(a2):\n', a1.dot(a2))  # matrix multiplication - works when number of a1.col == a2.row

print('a1 transpose:\n', a1.T)

a1:
 [[9 4 9]
 [9 1 6]
 [4 6 8]]
a2:
 [[7 1 5]
 [8 9 2]
 [7 3 3]]
a1*a2:
 [[63  4 45]
 [72  9 12]
 [28 18 24]]
a1.dot(a2):
 [[158  72  80]
 [113  36  65]
 [132  82  56]]
a1 transpose:
 [[9 9 4]
 [4 1 6]
 [9 6 8]]


In [13]:
# comparison
a1 = np.array([1, 2, 3, 4])
a2 = np.array([1, 5, 3, 2])

print(a1 == a2)     # element-wise comparison
print(np.array_equal(a1, a2))   # complete array comparison

[ True False  True False]
False


In [14]:
# logical operations
a1 = np.array([1, 0, 1, 1])
a2 = np.array([0, 1, 0, 1])

print(np.logical_and(a1, a2))

print(np.all([True, False, True]))  # returns True if all are True
print(np.any([False, True, True]))  # returns True if any one is True

[False False False  True]
False
True


In [15]:
# transcendental functions
a1 = np.array([0, 1, 2, 3, 4])
print(np.sin(a1))
print(np.log(a1))
print(np.exp(a1))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[       -inf  0.          0.69314718  1.09861229  1.38629436]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003]


c:\program files\python36\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [16]:
# reductions
a1 = np.arange(10)
print('a1:\n', a1)
print('a1 sum:', np.sum(a1))

a2 = np.arange(9).reshape(3,3)
print('a2:\n', a2)
print('a2 sum (axis=0):\n', np.sum(a2, axis=0))

a1:
 [0 1 2 3 4 5 6 7 8 9]
a1 sum: 45
a2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a2 sum (axis=0):
 [ 9 12 15]


In [17]:
a1 = np.array([3, 1, 5, 8])
print(a1.min())
print(a1.max())
print(a1.argmin())   # returns index
print(a1.argmax())   # returns index

1
8
1
3


In [18]:
# stats
a1 = np.array([1, 2, 2, 4, 5])
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))

2.8
2.0
1.46969384567


In [19]:
# load from txt
# data = np.loadtxt('file_name.txt')

In [20]:
# numpy broadcasting
a1 = np.tile(np.arange(0, 40, 10), (3,1))
print('a1:\n', a1)

a2 = np.arange(0, 4, 1)
print('a2:\n', a2)

print('a1+a2:\n', a1 + a2)

a1:
 [[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
a2:
 [0 1 2 3]
a1+a2:
 [[ 0 11 22 33]
 [ 0 11 22 33]
 [ 0 11 22 33]]


In [21]:
a1 = np.arange(0, 4, 1)
a2 = np.arange(0, 4, 1)
print('a1:\n', a1)
print('a2:\n', a2)
print('a1+a2 (before newaxis):\n', a1+a2)
# a1 + a2  ---> results in element wise addition, broadcasting won't work as both are 1D arrays 
# to do broadcasting
a1 = a1[:, np.newaxis]
print('a1+a2 (after newaxis):\n', a1+a2)

a1:
 [0 1 2 3]
a2:
 [0 1 2 3]
a1+a2 (before newaxis):
 [0 2 4 6]
a1+a2 (after newaxis):
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [22]:
# reshapings
a1 = np.array([[1, 2], [3, 4], [5, 6]])
print('a1:\n', a1)
print('a1 ravel:\n', a1.ravel())
print('a1 reshape:\n', a1.reshape(2,3))

a1:
 [[1 2]
 [3 4]
 [5 6]]
a1 ravel:
 [1 2 3 4 5 6]
a1 reshape:
 [[1 2 3]
 [4 5 6]]


In [23]:
# resize
a1 = np.arange(5)
print(a1)
a1.resize(10)
print(a1)

# note: resize won't work if the same values in memory is referenced by another variable

[0 1 2 3 4]
[0 1 2 3 4 0 0 0 0 0]


In [24]:
# sorting
a1 = np.arange(10).reshape(2,5)
print('a1:\n', a1)
a2 = np.sort(a1, axis=1)   # returns sorted elements
print('a1 (after np.sort):\n', a1)
print('a2:\n', a2)
a1.sort(axis=1)            # inplace sorting
print('a1:\n', a1)

a1:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
a1 (after np.sort):
 [[0 1 2 3 4]
 [5 6 7 8 9]]
a2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
a1:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
# sorting with fancy indexing
a1 = np.array([2, 3, 1, 4])
a2 = np.argsort(a1)
print('a2 (argsort):\n', a2)
print('a1[a2]:\n', a1[a2])

a2 (argsort):
 [2 0 1 3]
a1[a2]:
 [1 2 3 4]
